### ISSUE TITLE
Downloading gmp and gnupg

### ISSUE THREAD

**Issue by PatrickRyner** [learn-co-curriculum/macos-env-ruby#2]
I'm trying to download these programs, but I keep getting error messages and don't see how to correct them

"mac@macs-MacBook ~ % brew install gmp
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "gmp".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps."

Is there a better way to get these programs or fix this? Please advise

**Comment by ihollander** [comment]
Thanks for raising this issue. Based on your description, it sounds like the issue may be related to your environment setup rather than with the lesson itself or the instructions. The curriculum team monitors these issues so that we can fix typos and bugs in the curriculum, but we aren't equipped to provide support.

To get help with your question, you should either: 

- Reach out to your instructor (if you've started the program and have an instructor)
- Use the [#js-prework-support](https://flatiron-school.slack.com/archives/C01KEEVJU3Y) Slack channel (if you're working on the prework)
- Use the [Pair with a TC](https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team

Please re-open this issue if you believe the lesson needs to be updated.

Hope you are able to get this resolved!
